# Generated by Django 3.0.7 on 2020-06-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=150)),
                ('content', models.TextField(max_length=1500)),
                ('image', models.ImageField(blank=True, upload_to='post_image')),
            ],
        ),
    ]
