# Generated by Django 3.0.7 on 2020-06-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0004_auto_20200611_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.TextField(default='Anonymous User', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
